### ISSUE TITLE
Add buy/sell order limits (amount and cost) conditions

### ISSUE THREAD

**Issue by crashdemons** [crashdemons/GoldExchange#25]
potential limits settings to implement?

defaults should probably be reasonably accepting upper limits.  (for example there are 9*4 inventory slots with a potential of 64 items in each stack slot: a maximum of 2304 items)

However you can hold 9*4*64 GB = 2304 GB => 186624gn in currency
note: limiting the cost and unit price to 186624 ensures that no order (or single item) can be unbuyable.
Obviously, these defaults for cost,price only apply to the default currency system (gold nuggets,ingots,blocks) - modifications would need different defaults.

```
config:
   orders:
      ...
      buy:
         minQuantity: 1
         maxQuantity: 2304
         minTotalCost: 0
         maxTotalCost: 186624
         minUnitPrice: 0
         maxUnitPrice: 186624
      sell:
         minQuantity: 1
         maxQuantity: 2304
         minTotalCost: 0
         maxTotalCost: 186624
         minUnitPrice: 0
         maxUnitPrice: 186624
```

Conditions for these settings should be easy to make directly in GEPlugin.java.   since a lot of the buy and sell code is similar, it may be worthwhile making these checks in a new shared method, unless it's desirable to make an entire new class just for taking/validating user input...
